backend:
  name: git-gateway
  repo: SofieTorch/hub-ai-bolivia
  branch: main # Branch to update (optional; defaults to master)
media_folder: content/images
public_folder: /img
collections:
  - name: "knowledge-base"
    label: "Knowledge base"
    folder: "content/knowledge-base"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Previous", name: "prev", widget: "string" }
      - { label: "Next", name: "next", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
